name = "graph"
version = "1.0.0"

description = "Directed and undirected graphs"
licences = ["Apache-2.0"]
repository = { type = "github", user = "giacomocavalieri", repo = "graph" }

[dependencies]
gleam_stdlib = ">= 0.67.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
